### PR TITLE
fix(SRVKP-6734) and feature(SRVKP-6635): Postgres DB Dump + All Records Locust Test + Fix Locust Monitoring Setup 

### PR DESCRIPTION
**Pull request by rh-rahulshetty**
This PR introduces following changes:
- Fix Locust Monitoring issue in Hive cluster [SRVKP-6734](https://issues.redhat.com/browse/SRVKP-6734)
- Collect Tekton Results Postgres DB Dump [SRVKP-6635](https://issues.redhat.com/browse/SRVKP-6635)
- Fixed CI failing issue caused by "mstart" parameter used in --since flag for collecting results-api logs. Going forward the logs starting from the results-api started would be captured.
- Code Refactor and Cleanup
  - Removed "Aggrgated" locust metric and collecting test specific metrics (/log, /record, /records)
  - Removed "Aggregated" locust metric result from `runs-to-csv.sh`.
  - Created "cleanup_locust" method to clear any locust tests before and after the locust test execution.

### CODE REVIEW

**Review by siddardh-ra — APPROVED** [review]
Looks good :+1: !!

**Review by jhutar — APPROVED** [review]
/lgtm

**Review by siddardh-ra — APPROVED** [review]
/lgtm

**Review by siddardh-ra — APPROVED** [review]

**Review by khrm — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
