### PR TITLE
feat(SRVKP-4508): Add capability to benchmark OpenShift Pipelines across multiple namespaces 

### PR DESCRIPTION
**Pull request by rh-rahulshetty**
This PR introduces the following changes:

1. `benchmark.py`
    - Adds a new parser flag `--namespace (default=1)` that specifies number of namespaces to consider for benchmarking.
    
      When this flag is set to **1**, it will create only one namespace with the name **benchmark** (this is to maintain backward compatibility with existing test scenarios). But when the flag is set to different value, then it will consider namespaces with the following naming conventions: **benchmark1, benchmark2, benchmark3....**
    
    - Namespace state is captured in pipelinerun and taskrun events. The event watchers (PRsEventsWatcher and TRsEventsWatcher) listen for PR/TR events across all namespaces. 
    
    - PipelineRuns and TaskRuns stats (running/total/signed/etc) are collected at namespace level. **namespace** is stored in `benchmark-stats.csv` as an additional column.

    - To support `--wait-for-state` flag, the code now captures *namespace_wait_for_state_completed (set)* that keeps tracks of all the namespaces in which `--wait-for-state` is reached. Once this set reaches the total namespace count then the script is terminated.  

2. `ci-scripts/load-test.sh`
    - Adds a new env variable **TEST_NAMESPACE** (default=1) that is used across the benchmark script to denote no. of benchmarking namespaces to consider.
    
    - Supports creation and initialization of multiple namespaces during startup.
    
    - Pod information is collected from all the benchmark namespaces and consolidated into single *pods.json*. 

3. `tools/stats.sh`: PipelineRun and TaskRun information is collected from all the benchmark namespaces and consolidated into single *pipelineruns.json* and *taskruns.json* respectively.

4. `common/lib.sh`
    - *measure_signed_start* and *generate_more_start* methods takes in **TEST_NAMESPACE** into consideration.
    
    - *wait_for_prs_finished*  method looks up last "namespace" number of lines from `benchmark-stats.csv` and use average across all the namespaces to evaluate if the target number of PRs have completed or not.

### CODE REVIEW

**Review by jhutar — APPROVED** [review]
Awesome!

**Review by siddardh-ra — APPROVED** [review]
Looks good :+1:

**Pull request merged**
