### PR TITLE
feat(SRVKP-6127): Add Installing and Monitoring of Tekton Results

### PR DESCRIPTION
**Pull request by rh-rahulshetty**
# Changes
- The PR adds support for installing Tekton Results (both downstream/upstream) on OpenShift cluster as part of performance testing cluster setup.
- Introduces the following new environment variables for the Tekton Results setup:
  - **INSTALL_RESULTS**: Whether to install Tekton Results during the cluster setup. 
  (Possible Values: true/false | Default: false)
  - **DEPLOYMENT_TYPE_RESULTS**: Which instance of Tekton Results to install 
  (Possible Values: upstream/downstream | Default: downstream)
  - **DEPLOYMENT_RESULTS_UPSTREAM_VERSION**: Used when **DEPLOYMENT_TYPE_RESULTS** set to *upstream* and specifies which version of upstream Tekton Results to install in cluster. 
  (Values based on official [release](https://github.com/tektoncd/results/releases) | Default: latest)
- Additionally, the PR also adds the monitoring of following pods: **tekton-results-api** and **tekton-results-watcher**

### CODE REVIEW

**Review by jhutar — APPROVED** [review]
/lgtm

**Review by siddardh-ra — APPROVED** [review]
Looks great

**Review by khrm — COMMENTED** [review]
/lgtm

**Pull request merged**
